version: '3.1'

services :
  db:
    image: cgloveut/educatationdb:v1
    command: mysqld --default-authentication-plugin=mysql_native_password
    networks: 
      - dev
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks: 
      - dev

networks: 
    dev: