version: '3.1'

services :
  db:
    image: cgloveut/educatationdb:v1
    command: mysqld --default-authentication-plugin=mysql_native_password
    networks: 
      - dev
  app:
    build: .
    command: yarn start:dev
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    environment:
      DATABASE_URL: db
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks: 
      - dev

networks: 
    dev: