version: '3.1'

services :
  db:
    image: cgloveut/educatationdb:v1
    command: mysqld --default-authentication-plugin=mysql_native_password
  app:
    image: cgloveut/educationinsurance-backend:v1
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure 