apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodeapi
    name: nodeapi
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: nodeapi
